name       : clj-kondo
version    : 2023.09.07
release    : 7
source     :
    - https://github.com/clj-kondo/clj-kondo/archive/refs/tags/v2023.09.07.tar.gz : 4840467f65cbb122de04fbd1e7225f252a1dd4c515761e0ce6eed2b46c4839c2
license    : EPL-1.0
component  : programming.tools
networking : yes
summary    : Clojure(script) and EDN linting
description: |
    clj-kondo performs static analysis on Clojure, ClojureScript and EDN, without the need of a running REPL. It informs you about potential errors while you are typing.
builddeps  :
    - leiningen
    - graalvm
environment: |
    export GRAALVM_HOME=/usr/share/graalvm/
    export JAVA_HOME=/usr/share/graalvm/
    export JAVA_CMD=/usr/share/graalvm/bin/java
build      : |
    # make lein use a temporary location for deps
    sed -i '7 i :local-repo "/tmp/.m2/repo"' project.clj
    lein uberjar
    ./script/compile

install    : |
    install -Dm00755 ./clj-kondo $installdir/usr/bin/clj-kondo

